description: .b-offer__description
image: .b-offer__preview
discount: .b-offer__discount
price_new: .b-offer__price-new
price_old: .b-offer__price-old
quantity: .b-offer__quantity
date: .b-offer__dates